settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: sagemedia-co
    name: sagemedia.co
    description: 'Sage Media'
    url: 'https://sagemedia.co'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
        
  - id: humanesocietyofthedunes-com
    name: humanesocietyofthedunes.com
    description: 'Humane Society of the Dunes'
    url: 'https://humanesocietyofthedunes.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: cfpropertydevelopment-com
    name: cfpropertydevelopment.com
    description: 'CF Property Development'
    url: 'https://cfpropertydevelopment.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
        
  - id: cullermedia-com
    name: cullermedia.com
    description: 'Culler Media'
    url: 'https://cullermedia.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
        
  - id: reimarketingbook-com
    name: reimarketingbook.com
    description: 'REI Marketing Book'
    url: 'https://reimarketingbook.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
        
  - id: reimarketingweekly-com
    name: reimarketingweekly.com
    description: 'REI Marketing Weekly'
    url: 'https://reimarketingweekly.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
        
  - id: mikeandrade-com
    name: mikeandrade.com
    description: 'Mike Andrade'
    url: 'https://mikeandrade.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
        
  - id: laportecountydems-com
    name: laportecountydems.com
    description: 'La Porte County Indiana Democrats'
    url: 'https://laportecountydems.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
        
  - id: jimwieser-com
    name: jimwieser.com
    description: 'Jim Wieser'
    url: 'https://jimwieser.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
